### ISSUE TITLE
Detect set formatoptions+=r

### ISSUE THREAD

**Issue by davidosomething** [lambdalisue/vim-backslash#2]
Plugin should detect `fo+=r`, currently breaks comment continuation. Default behavior with `set formatoptions+=r`:
### no vim-backslash

before:

``` viml
" My comment. |
```

after pressed o:

``` viml
" My comment.
" |
```
### with vim-backslash

before:

``` viml
" My comment. |
```

after pressed o:

``` viml
" My comment.
|
```

**Comment by lambdalisue** [comment]
Make sense. I'll implement the feature :-)

**Comment by lambdalisue** [comment]
This should be implemented on https://github.com/lambdalisue/vim-backslash/commit/d4bb5c5ccd78ee8ac1766fcbfc3fbd49cebeed72. Please check and close if you are satisfy :smiley: @davidosomething

**Comment by davidosomething** [comment]
LGTM! 👍
