### ISSUE TITLE
Incorrect coffeescript detection

### ISSUE THREAD

**Issue by davidosomething** [lambdalisue/vim-backslash#3]
Interpolated multiline string, `|` is the cursor

``` coffee
      msg.send "`mine` to build your previous:
        #{userBuild.branch} on #{userBuild.target}"|
```

press `o` yields:

``` coffee
      msg.send "`mine` to build your previous:
        #{userBuild.branch} on #{userBuild.target}"|
        #
```

Should not have continued `#` since it is not a continuation character

**Comment by lambdalisue** [comment]
Are you sure that the behaviour comes from this plugin? Ideally this plugin should not affect the other filetypes.

**Comment by davidosomething** [comment]
Oh you are right, it is vim behavior
