### ISSUE TITLE
<CR> overwrites existing mappings from other plugins (e.g. auto-pairs, lexima)

### ISSUE THREAD

**Issue by kristijanhusak** [lambdalisue/vim-backslash#8]
Hi,

i'm trying to use vim-backslash together with https://github.com/jiangmiao/auto-pairs, but it doesn't work. I can't really figure out why, so maybe you can help: 

Min. vimrc:

```vimL
set rtp+=/path/to/vim-backslash
set rtp+=/path/to/auto-pairs
```

When i press Enter i get printed out `<Plug>(backslash-CR-i)` instead of new line. I tried messing around with auto-pairs config, but with no luck.

This is what i have when i do `:imap <CR>`

```
i  <CR>        &@<Plug>(backslash-CR-i)<SNR>38_AutoPairsReturn
```

and a maparg()
```
{'silent': 1, 'noremap': 1, 'lhs': '<CR>', 'mode': 'i', 'nowait': 0, 'expr': 0, 'sid': 38, 'rhs': '<Plug>(backslash-CR-i)<SID>AutoPairsReturn', 'buffer': 1}
```

**Comment by lambdalisue** [comment]
I've no idea about auto-pairs but I'm using similar plugin and that works well with vim-backslash.
https://github.com/cohama/lexima.vim

**Comment by kristijanhusak** [comment]
That looks good. I found only one issue with it, which looks like it's also caused by vim-backslash.
lexima has https://github.com/cohama/lexima.vim#endwise-rules which are great, but they are not working with vim-backslash. Do you know why?

**Comment by lambdalisue** [comment]
lt seems both are working on my environment.

[![asciicast](https://asciinema.org/a/t2GO3wcspew8qUhlw4x3XgEhY.svg)](https://asciinema.org/a/t2GO3wcspew8qUhlw4x3XgEhY)

**Comment by kristijanhusak** [comment]
It also works for me when i create new file and start editing it, but when i open an existing vim file, it won't work for some reason.

**Comment by lambdalisue** [comment]
Finally, reproduced! I'll investigate 👍

**Comment by adriaanzon** [comment]
I'd say, at least give users a way to disable the mapping that gets defined [here](https://github.com/lambdalisue/vim-backslash/blob/a56a8b5559eeb7bfb4863db2f630ea41d5e5eff3/after/ftplugin/vim/backslash.vim#L35-L37), so users can invoke `<Plug>(backslash-CR-i)` manually. Endwise has a `g:endwise_no_mappings` variable, for example.

I currently have my own `<CR>` mapping that combines delimitMate, bullets.vim, and endwise, and I want to add vim-backslash to it:

```vim
imap <silent> <expr> <CR> mappings#super_cr()

function! mappings#super_cr()
  if pumvisible() && !empty(v:completed_item)
    return "\<C-y>"
  endif

  if exists('g:loaded_delimitMate') && b:delimitMate_enabled
    call s:temporary_matchpairs()
    if delimitMate#WithinEmptyPair()
      return "\<Plug>delimitMateCR"
    endif
  end

  if index(g:bullets_enabled_file_types, &filetype) != -1 && col('$') == col('.')
    return "\<Esc>:InsertNewBullet\<CR>"
  endif

  return "\<CR>\<Plug>DiscretionaryEnd"
endfunction
```

**Comment by kristijanhusak** [comment]
@adriaanzon this looks good. What does `s:temporary_matchpairs()` do?

**Comment by adriaanzon** [comment]
@kristijanhusak it is a hack to make delimitMate's `<CR>` behavior work for html tags, without using the `>:<` pair for delimitMate's main behavior. 

```vim
function! s:temporary_matchpairs()
  if exists('s:matchpairs_timer')
    call timer_stop(s:matchpairs_timer)
  endif
  if !exists('b:delimitMate_matchpairs')
    let b:delimitMate_matchpairs = g:delimitMate_matchpairs . ',>:<'
    silent DelimitMateReload
  endif
  let s:matchpairs_timer = timer_start(100, {-> execute(['unlet! b:delimitMate_matchpairs', 'DelimitMateReload'])})
endfunction
```

**Comment by lambdalisue** [comment]
I've added ~`g:backslash_disable_default_mappings`~ `g:vim_backslash_disable_default_mappings` as @adriaanzon suggested.
Sorry for late.
