### ISSUE TITLE
do not add if inside a code blocks

### ISSUE THREAD

**Issue by prabirshrestha** [lambdalisue/vim-backslash#9]
```vim
lua <<EOF
    function hello()
    end
EOF
```

**Comment by lambdalisue** [comment]
~It would be nice but I think using https://github.com/Shougo/context_filetype.vim is enough.~

I've misunderstood context_filetype.vim. So it seems we need to support context_filetype.vim

**Comment by lambdalisue** [comment]
New feature has implemented. Use `g:vim_backslash#preventers` with https://github.com/Shougo/context_filetype.vim like

```vim
let g:vim_backslash#preventers = [
      \ { -> context_filetype#get_filetype() !=# 'vim' },
      \]
```

**Comment by prabirshrestha** [comment]
That works. Thanks for the quick turnaround!
